### ISSUE TITLE
Bot doesn't reply to all

### ISSUE THREAD

**Issue by shrayasr** [shrayasr/TheHexBot#4]
If many people are mentioned in a tweet, bot should reply to all of them.

Example: https://twitter.com/raghothams/status/918356230862598145 mentions `@shrayasr` in the tweet but the reply https://twitter.com/thehexbot/status/918359352939044864 doesn't mention them.

**Comment by balaji-s** [comment]
Hi 

I cloned the project and opened it in vs code. I ran dotnet restore and got this warning, 
![imagesharp](https://user-images.githubusercontent.com/22422768/32322733-a1537402-bfeb-11e7-99f4-f940e1728080.PNG)


and i cannot compile the code due to the following issue, any suggestions on how to solve the build issue
![image](https://user-images.githubusercontent.com/22422768/32322787-c97e4c54-bfeb-11e7-928b-45d403d877e6.png)

**Comment by shrayasr** [comment]
Must be because ImageSharp is still unstable. I'll have a look into it and update the project accordingly. 

Thanks for reporting 🙌

**Comment by shrayasr** [comment]
@balaji-s #5 is fixed now. Let me know if you still face problems. Note that this builds ONLY with VS2017

**Comment by balaji-s** [comment]
Thanks for fixing the build issue :-)
